# Generated by Django 4.2.30 on 2026-05-30 04:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalsFaculty',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.globalsextrainfo')),
            ],
            options={
                'db_table': 'globals_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(help_text='Name of the database that was backed up', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Size of the backup file in bytes')),
                ('duration_ms', models.BigIntegerField(default=0, help_text='Duration of the backup in milliseconds')),
                ('file_path', models.CharField(blank=True, default='', help_text='Path to the backup file on disk', max_length=500)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if backup failed')),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom (cron)')], default='daily', max_length=20)),
                ('hour', models.IntegerField(default=2, help_text='Hour (0-23) in UTC')),
                ('minute', models.IntegerField(default=0, help_text='Minute (0-59)')),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week for weekly schedule (0=Mon, 6=Sun)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly schedule (1-28)', null=True)),
                ('cron_expression', models.CharField(blank=True, default='', help_text='Full cron expression: minute hour day month weekday', max_length=100)),
                ('retain_last_n', models.IntegerField(default=7, help_text='Keep only the last N successful backups (0 = keep all)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backup_schedules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=200)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('response_time_ms', models.IntegerField(default=0, help_text='DB ping response time in ms')),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'health_checks',
                'ordering': ['-checked_at'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='discipline',
            table='programme_curriculum_discipline',
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=200)),
                ('source_backup_created_at', models.DateTimeField(blank=True, help_text='Snapshot of the source backup timestamp (kept even if backup is deleted)', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('duration_ms', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_backup', models.ForeignKey(blank=True, help_text='The backup this restore was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='api.backuprecord')),
            ],
            options={
                'db_table': 'restore_records',
                'ordering': ['-started_at'],
                'managed': True,
            },
        ),
    ]
