# Generated by Django 4.2.30 on 2026-07-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_globalsfaculty_staff_backuprecord_backupschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='encrypted',
            field=models.BooleanField(default=False, help_text='Whether the dump file is encrypted at rest (Fernet)'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='academic_information_student',
        ),
    ]
