"""Emit the reverse proxy's path map from the module registry.

    manage.py emit_routes --nginx > /etc/nginx/snippets/fusion-routes.conf

Derived, never authored: the registry that draws the sidebar also routes the
traffic, so the two cannot disagree. A module moving between apps changes its
`app` and nothing else — the path belongs to the module, so bookmarks survive.
"""
from django.core.management.base import BaseCommand, CommandError

from iam.models import IamModule

#: Upstream per app. Overridden with --upstream app=name, repeatable.
DEFAULT_UPSTREAMS = {"legacy": "fusion_legacy", "integrated": "fusion_platform"}

HEADER = """# Generated by `manage.py emit_routes` — do not edit.
# One block per module. The catch-all for `/` stays in the server block, last.
"""

BLOCK = """
# {code} -> {app}
location ^~ {base}/ {{
    include proxy_params;
    proxy_pass http://{upstream};
}}
location ^~ /api/v1{base}/ {{
    include proxy_params;
    proxy_pass http://{upstream};
}}
"""


class Command(BaseCommand):
    help = "Emit the reverse-proxy path map from the module registry"

    def add_arguments(self, parser):
        parser.add_argument("--nginx", action="store_true",
                            help="Emit nginx location blocks (the only format).")
        parser.add_argument("--upstream", action="append", default=[],
                            metavar="APP=UPSTREAM",
                            help="Override an app's upstream. Repeatable.")

    def handle(self, *args, **opts):
        if not opts["nginx"]:
            raise CommandError("Pass --nginx; there is no other format yet.")

        upstreams = dict(DEFAULT_UPSTREAMS)
        for item in opts["upstream"]:
            app, _, name = item.partition("=")
            if not app or not name:
                raise CommandError(f"--upstream wants APP=UPSTREAM, got {item!r}")
            upstreams[app] = name

        modules = IamModule.objects.filter(status="active").order_by("code")
        if not modules:
            raise CommandError("No active module is registered — refusing to "
                               "emit a map that routes nothing.")

        unknown = sorted({m.app for m in modules} - set(upstreams))
        if unknown:
            raise CommandError(
                f"No upstream for {', '.join(unknown)}. Pass --upstream "
                f"{unknown[0]}=<name>, or the paths would 404 in production.")

        self.stdout.write(HEADER)
        seen: set[str] = set()
        for m in modules:
            # base_path, never the code: placement_cell is served at /placement.
            base = m.base_path.rstrip("/")
            if base in seen:
                raise CommandError(
                    f"Two modules claim {base!r}; one would shadow the other.")
            seen.add(base)
            self.stdout.write(BLOCK.format(code=m.code, app=m.app, base=base,
                                           upstream=upstreams[m.app]))
