# Generated by Django 4.2.30 on 2026-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0008_alter_iamuser_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamdesignationmodule',
            name='source',
            field=models.CharField(default='erp', max_length=32),
        ),
    ]
