# Generated by Django 4.2.30 on 2026-09-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0009_alter_iamdesignationmodule_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=48)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='FaCircle', max_length=48)),
                ('base_path', models.CharField(max_length=80)),
                ('nav_section', models.CharField(default='Modules', max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='planned', max_length=16)),
                ('app', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'iam_module',
                'ordering': ['nav_section', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='IamNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(default='FaCircle', max_length=48)),
                ('to', models.CharField(max_length=160)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('source', models.CharField(max_length=32)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='iam.iammodule')),
            ],
            options={
                'db_table': 'iam_nav_item',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='iammodule',
            constraint=models.UniqueConstraint(fields=('code', 'source'), name='iam_module_unique_per_publisher'),
        ),
        migrations.AddConstraint(
            model_name='iamnavitem',
            constraint=models.UniqueConstraint(fields=('code', 'source'), name='iam_nav_item_unique_per_publisher'),
        ),
    ]
