# Generated by Django 4.2.30 on 2026-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0010_iammodule_iamnavitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamuser',
            name='last_selected_role',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
