# Generated by Django 4.2.30 on 2026-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0011_iamuser_last_selected_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='usernames_released',
            field=models.IntegerField(default=0),
        ),
    ]
