# Generated by Django 4.2.30 on 2026-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_syncrun_usernames_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iamdesignationmodule',
            name='source',
            field=models.CharField(max_length=32),
        ),
    ]
