# Generated by Django 4.2.30 on 2026-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0013_alter_iamdesignationmodule_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iamuser',
            name='resume_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
